name: Create .exe

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Create version files
        run: |
          create-version-file "version main.yml" --outfile "version main.rc"
          create-version-file "version installer.yml" --outfile "version installer.rc"
      
      - name: build main
        run: |
          pyinstaller main.py --clean --windowed --onefile --name "Tangente Neomatik" --add-data "assets\icon.ico;assets" --add-data "assets\Sprites.png;assets" --add-data "settings\settings.json;settings" --icon "assets\icon.ico" --version-file "version main.rc" --distpath "."

      - name: debug
        run: |
          git add "Tangente Neomatik.exe"
          git commit -m "Auto generated .exe files"
      
